// Updated server.ts

function parseJDAI() {
    // Some code...
    const model = 'gemini-1.5-flash'; // updated from 'gemini-2.0-flash'
    // Some more code...
}

function generateQuestionsAI() {
    // Some code...
    const model = 'gemini-1.5-flash'; // updated from 'gemini-2.0-flash'
    // Some more code...
}

function evaluateCandidateAI() {
    // Some code...
    const model = 'gemini-1.5-flash'; // updated from 'gemini-2.0-flash'
    // Some more code...
}